# Generated by Django 4.2.9 on 2024-02-07 15:19

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("investor", "Investor"), ("startup", "Startup")],
                        max_length=8,
                        verbose_name="Role",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Username"
                    ),
                ),
                ("password", models.CharField(max_length=15, verbose_name="Password")),
                (
                    "email",
                    models.EmailField(
                        max_length=20, unique=True, verbose_name="Email Address"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Last Name"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "users",
                "ordering": ["email"],
                "indexes": [
                    models.Index(fields=["email"], name="users_user_email_6f2530_idx")
                ],
            },
        ),
    ]
