# Generated by Django 4.2.10 on 2024-02-09 11:43

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_date_joined_user_is_active_user_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("investor", "Investor"),
                    ("startup", "Startup"),
                ],
                max_length=8,
                verbose_name="Role",
            ),
        ),
    ]
