# Generated by Django 4.2.10 on 2024-02-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_investor_founder"),
    ]

    operations = [
        migrations.AddField(
            model_name="founder",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AddField(
            model_name="investor",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
    ]
