# Generated by Django 4.2.10 on 2024-02-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_founder_is_active_investor_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("investor", "Investor"),
                    ("startup", "Startup"),
                ],
                default=None,
                max_length=10,
                null=True,
            ),
        ),
    ]
