version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: chnu-practics-2024:v1
    environment:
      - PORT=8080
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: sh -c "/app/migrate.sh && /app/entrypoint.sh"
