[project]
name = "ChNu-Practics-2024"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "django>=4.2,<4.3",
  "djangorestframework",
  "gunicorn",
] 

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
