# Generated by Django 4.2.10 on 2024-02-19 18:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("startups", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="startup",
            name="startup_founders",
        ),
    ]
