# Generated by Django 4.2.10 on 2024-02-20 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StartupFounder',
        ),
    ]
