# Generated by Django 4.2.10 on 2024-02-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_founder_is_active_investor_is_active'),
        ('startups', '0002_delete_startupfounder'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='founders',
            field=models.ManyToManyField(to='users.founder'),
        ),
    ]
