# Generated by Django 4.2.10 on 2024-02-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_startup_founders'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Bio'),
        ),
    ]
