# Generated by Django 4.2.10 on 2024-02-19 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("startups", "0003_startupfounder_user_alter_startupfounder_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="startupfounder",
            name="startup_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="founders",
                to="startups.startup",
            ),
        ),
    ]
