# Generated by Django 4.2.10 on 2024-02-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_startup_founders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='startup',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('B', 'Big'), ('L', 'Large')], default='S', help_text='Startup size', max_length=1),
        ),
    ]
