# Generated by Django 4.2.10 on 2024-02-21 15:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_startup_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=64, verbose_name='Project Name')),
                ('type', models.CharField(blank=True, choices=[('P', 'Project'), ('I', 'Idea')], default='S', help_text='Project type', max_length=1)),
                ('created_at', models.DateTimeField()),
                ('description', models.CharField(max_length=50)),
                ('media_url', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='startup',
            name='projects',
            field=models.ManyToManyField(to='startups.project'),
        ),
    ]
