# Generated by Django 4.2.10 on 2024-02-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0005_project_startup_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Bio'),
        ),
    ]
