# Generated by Django 4.2.10 on 2024-02-21 16:53

from django.db import migrations
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0007_alter_project_description_alter_project_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='media_url',
            field=pictures.models.PictureField(aspect_ratios=[None, '1/1', '3/2', '16/9'], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['WEBP'], grid_columns=12, pixel_densities=[1, 2], upload_to='avatars'),
        ),
    ]
