# Generated by Django 4.2.10 on 2024-02-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0008_alter_project_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='media_url',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
