# Generated by Django 4.2.10 on 2024-02-27 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_alter_startup_location_alter_startup_size'),
        ('startups', '0009_alter_project_media_url'),
    ]

    operations = [
    ]
